### ISSUE TITLE
ControlClient.CLI, ControlClient.GUI projects

### ISSUE THREAD

**Issue by bdpy** [AdaptiveConsulting/ReactiveTrader#137]
What is the right way to launch these projects? I open ReactiveTrader-WPF.sln, whenever I try to run ControlClient.CLI with opened Server.GUI there is the following error (while Server.GUI and Client.GUI run successfully):

2016-03-02 20:11:55,587 INFO  -   ____  ____    __    ___  ____  ____  _  _  ____
2016-03-02 20:11:55,592 INFO  -  (  _ \( ___)  /__\  / __)(_  _)(_  _)( \/ )( ___)
2016-03-02 20:11:55,593 INFO  -   )   / )__)  /(__)\( (__   )(   _)(_  \  /  )__)
2016-03-02 20:11:55,593 INFO  -  (_)\_)(____)(__)(__)\___) (__) (____)  \/  (____)
2016-03-02 20:11:55,593 INFO  -    ___  _____  _  _  ____  ____  _____  __
2016-03-02 20:11:55,593 INFO  -   / __)(  _  )( \( )(_  _)(  _ \(  _  )(  )
2016-03-02 20:11:55,593 INFO  -  ( (__  )(_)(  )  (   )(   )   / )(_)(  )(__
2016-03-02 20:11:55,593 INFO  -   \___)(_____)(_)\_) (__) (_)\_)(_____)(____)
Please enter your name (logging purposes only):
asdf
Please enter your authorization token:
asdf
2016-03-02 20:11:59,478 INFO  - Initializing reactive trader API...
2016-03-02 20:11:59,525 INFO  - Reactive trader API initialized in 38ms
2016-03-02 20:11:59,525 INFO  - API Connecting...
2016-03-02 20:11:59,728 INFO  - ConnectionStatus: Connected, Server: http://localhost:8080, TransportName:serverSentEven
ts
2016-03-02 20:11:59,743 INFO  - API Connected.
2016-03-02 20:11:59,743 INFO  - Enter currency pair symbol and new state. Either E or D for enabled or disabled, or A or
 S for active or stale

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Ther
e was an error invoking Hub method 'ControlHub.GetCurrencyPairStates'.
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at Adaptive.ReactiveTrader.ControlClient.CLI.Program.<RunLoop>d__3.MoveNext() in C:\OneDrive\Projects\DemoOther\React
iveTrader\src\Adaptive.ReactiveTrader.ControlClient.CLI\Program.cs:line 79
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Adaptive.ReactiveTrader.ControlClient.CLI.Program.Main(String[] args) in C:\OneDrive\Projects\DemoOther\ReactiveTr
ader\src\Adaptive.ReactiveTrader.ControlClient.CLI\Program.cs:line 34

**Comment by raybooysen** [comment]
Hi

What are you trying to achieve?  Run the desktop app and web app?

**Comment by bdpy** [comment]
I just wanted to run CLI, command line project to see basic functionality. What is the right way to launch it?

**Comment by raybooysen** [comment]
I've just pulled the code, battling to compile to be honest.  Will have to follow up hopefully later today

**Comment by LeeCampbell** [comment]
The `Adaptive.ReactiveTrader.ControlClient.CLI` and `Adaptive.ReactiveTrader.ControlClient.GUI` tools are for controlling a deployed instance of the Server. If you were to use them, you would need to populate the app settings to be able to know which server you are connecting to and passing the authentication credentials.

    <appSettings>
      
      <add key="servers" value="http://localhost:8080" />
      <add key="AuthToken" value="" />
      <add key="Username" value="" />
    </appSettings>

To be honest, this is the set up I use (and can run from current master)

 1. get latest master
 2. open the _src\ReactiveTrader-WPF.sln_ solution
 3. set `Adaptive.ReactiveTrader.Client.GUI` and `Adaptive.ReactiveTrader.Server.GUI` as start up projects
 4. hit F5 (rebuild, get nugets etc)

I don't have experience running the web stack however.

**Comment by bdpy** [comment]
`Client.GUI` and `Server.GUI` run successfully together (as I have mentioned in the question), still I couldn't run `ControlClient.CLI`. But I also understood that I do not need it. Thanks.
